# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"

# Uncomment the lines below to configure your website in a second language.
# [de]
#  languageCode = "de"
#  contentDir = "content/de"
#  title = "Sebastian Siuda"
#  [de.params]
#    description = "Site description in German..."
#  [[de.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
